api_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.shortcuts import reverse

from api_app import views as api_views


urlpatterns = [
    path('check/', api_views.check_settings, name='check_settings'),
    path('client/<uuid:clientuuid>/computer', api_views.add_computer_to_client, name='add_computer'),
    path('clients', api_views.get_all_clients, name='get_all_clients'),
    path('domains', api_views.get_domain_clients, name='get_domain_clients'),
    path('domain/<uuid:clientuuid>', api_views.get_domain_info, name='get_domain_info'),
    re_path(r'^.*$', api_views.missed_request, name='missed'),
]

clientmanagement/testmodule/urls.py
"""
URL patterns for testmodule
"""
from django.urls import path

from clientmanagement.testmodule import views as testmodule_views

urlpatterns = [
    path('', testmodule_views.testmodule, name='testmodule'),
]

clientmanagement/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.shortcuts import reverse

from clientmanagement import views as clientmanagement_views
from clientmanagement import loginform as clientmanagement_loginform
from clientmanagement import generatefileviews as generate_files
from models import views as models_views
from models.email import mailbox


urlpatterns = [
    path('clients/', clientmanagement_views.allclientsview, name='allclients'),
    path('computers/', clientmanagement_views.allcomputersview, name='allcomputers'),
    path('people/', clientmanagement_views.allpeopleview, name='allpeople'),

    path('clients/<int:clientid>', clientmanagement_views.clientview, name='oneclient'),
    path('clients/<int:clientid>/printer', models_views.printerForm, name='clientprinter'),
    path('clients/<int:clientid>/computer', models_views.computerForm, name='clientcomputer'),
    path('clients/<int:clientid>/person', models_views.personForm, name='clientperson'),
    path('clients/<int:clientid>/domain', models_views.domainForm, name='clientdomain'),
    path('clients/<int:clientid>/router', models_views.routerForm, name='clientrouter'),
    path('clients/<int:clientid>/netequipment', models_views.otherNetEquipmentForm, name='clientothernetequip'),
    path('clients/<int:clientid>/joindomainfile', generate_files.downloadConnectDomainFile, name='clientjoindomainfile'),
    path('clients/<int:clientid>/addcomputersoftware', generate_files.downloadAddComputerSoftware, name='clientaddcomputersoftware'),
    path('clients/<int:clientid>/addcomputerconfig', generate_files.downloadAddComputerConfigFile, name='clientaddcomputerconfig'),

    path('tickets/submit', models_views.submitTicketForm, name='ticket_submit'),
    path('tickets/submitted', clientmanagement_views.ticketdoneview, name='ticket_submitted'),
    path('tickets/<int:ticketid>/change', models_views.changeTicketForm, name='ticket_change'),
    path('tickets/<uuid:ticketuuid>', models_views.viewTicketDirectView, name='ticket_view_direct'),
    re_path(r'^tickets/(?P<ticketuuid>\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)/files/(?P<filename>[a-zA-Z0-9\.\(\)_\-+=!@#%]+)', models_views.downloadFileFromTicket, name='get_ticket_file'),
    re_path(r'^tickets/(?P<ticketuuid>\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)/v/files/(?P<filename>[a-zA-Z0-9\.\(\)_\-+=!@#%]+)', models_views.viewFileFromTicket, name='get_ticket_file_view'),
    re_path(r'^tickets/(?P<ticketuuid>\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)/(?P<commentid>\d+)/files/(?P<filename>[a-zA-Z0-9\.\(\)_\-+=!@#%]+)', models_views.downloadFileFromComment, name='get_comment_file'),
    re_path(r'^tickets/(?P<ticketuuid>\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)/(?P<commentid>\d+)/v/files/(?P<filename>[a-zA-Z0-9\.\(\)_\-+=!@#%]+)', models_views.viewFileFromComment, name='get_comment_file_view'),
    path('tickets/<uuid:ticketuuid>/addcomment', models_views.addCommentToTicketView, name='ticket_add_comment'),
    re_path(r'^tickets/(?P<reqtype>(a|c|o|))', clientmanagement_views.allticketsview, name='alltickets'),

    path('note', models_views.AddSecretNoteView, name='new_note'),
    path('notes/', models_views.allSecretNotesView, name='all_notes'),
    re_path(r'^notes/(?P<reqtype>(|a|u))$', models_views.allSecretNotesView, name='all_notes'),
    path('notes/<int:noteid>', models_views.SecretNoteInternalView, name='note_internal'),
    path('notes/<int:noteid>/change', models_views.changeTicketForm, name='note_change'),
    path('notes/c/<uuid:noteuuid>', models_views.viewSecretNoteViewClose, name='note_close'),
    path('notes/o/<uuid:noteuuid>', models_views.viewSecretNoteViewOpen, name='note_open'),

    re_path(r'^tool/(?P<tool_type>(l|f))$', models_views.AddNewToolView, name='new_tool'),
    re_path(r'^tools/(?P<tool_type>(l|f|))$', clientmanagement_views.allToolsView, name='all_tools'),
    path('tool/f/d/<uuid:tooluuid>', models_views.downloadToolPublic, name='download_tool_public'),
    path('tool/f/d/p/<uuid:tooluuid>', models_views.downloadTool, name='download_tool'),

    path('statistics/', clientmanagement_views.statisticsview, name='statistics'),
    path('client', models_views.clientForm, name='newclient'),
    path('client/<int:clientid>/r', models_views.downloadRouterSettings, name='download_router_settings'),

    path('wiki/', clientmanagement_views.allWikiArticlesView, name='all_wiki'),
    path('wiki/new', models_views.createWikiArticle, name='wiki_new'),
    path('wiki/<uuid:wikiuuid>', clientmanagement_views.wikiArticleView, name='wiki_art'),

    path('updates/', clientmanagement_views.systemupdatesview, name='updates'),
    path('updates/post', models_views.PostSystemUpdate, name='postupdate'),

    path('usermanagement/', clientmanagement_views.usermanagement, name='usermanagement'),
    path('usermanagement/adduser', models_views.addUserForm, name='adduser'),
    path('', clientmanagement_views.homepage, name='homepage'),

    path('me', clientmanagement_views.userpersonalpage, name='personal_page'),
    path('me/<int:deleted>/<int:deletedpage>', clientmanagement_views.userpersonalpage, name='personal_page_uri'),
    path('me/delete_api', clientmanagement_views.deletepersonalapikey, name='delete_my_api_key'),
    path('me/cms_interactive', generate_files.downloadUserCMSInteractionSoftware, name='cms_interactive_software'),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(form_class=clientmanagement_loginform.my_reset_password_form, 
    html_email_template_name='registration/forgot_password.htm'), 
    {'password_reset_form':clientmanagement_loginform.my_reset_password_form, 
    'form_class': clientmanagement_loginform.my_reset_password_form}, 'password_reset'),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=clientmanagement_loginform.MyAuthLoginForm), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('api/', include('api_app.urls')),
    re_path(r'^.*$', clientmanagement_views.homepage),
    path('testmodule/', include('clientmanagement.testmodule.urls')),
]


mailbox.initiateEmailCheck()

clientmanagement/models.py
from django.db import models

class Client(models.Model):
    name = models.CharField('Client Name', max_length=40)
    address = models.CharField('Client Address', max_length=120)
    phone = models.CharField('Phone Number', max_length=20)

models/computers.py
from django.db import models
from datetime import datetime
from models import networkequipment
from django.core.validators import MaxValueValidator, MinValueValidator
from models import person
from models import client

class Computer(networkequipment.NetworkEquipment):
    OPERATING_SYSTEMS = (
        ('W10', 'Windows 10'),
        ('W8', 'Windows 8'),
        ('W7', 'Windows 7'),
        ('WS19', 'Windows Server 2019'),
        ('WS16', 'Windows Server 2016'),
        ('WS12', 'Windows Server 2012'),
        ('WS08', 'Windows Server 2008'),
        ('WS03', 'Windows Server 2003'),
        ('MJ', 'MacOS Majovang'),
        ('MHS', 'MacOS High Siera'),
        ('MS', 'MacOS Siera'),
        ('WXP', 'Windows XP'),
        ('WO', 'Windows Other'),
        ('MO', 'MacOS Other'),
        ('O', 'Other'),
    )
    MANUFACTURER = (
        ('D', 'DELL'),
        ('H', 'HP'),
        ('L', 'Lenovo'),
        ('M', 'Microsoft'),
        ('G', 'Apple'),
        ('A', 'Asus'),
        ('S', 'Sony'),
        ('C', 'Acer'),
        ('O', 'Other')
    )
    computername = models.CharField('Computer Name', max_length=40, null=False)
    operatingsystem = models.CharField(max_length=4, null=False, default='W10', blank=False, choices=OPERATING_SYSTEMS)
    manufacturer = models.CharField(max_length=1, null=False, default='D', blank=False, choices=MANUFACTURER)
    model = models.CharField(max_length=60, null=True, default='', blank=True)
    compmonth = models.IntegerField("Recieved Month (enter a number)", blank=True, null=True, default=None, validators=[MaxValueValidator(12), MinValueValidator(1)])
    compyear = models.IntegerField("Recieved Year (enter a number)", blank=True, null=True, default=None, validators=[MaxValueValidator(2030), MinValueValidator(2000)])
    serialnumber = models.CharField(max_length=60, null=True, default='', blank=True)
    user = models.ManyToManyField(person.Person, blank=True, related_name='computer')
    
    def __str__(self):
        return self.computername

models/othernetequip.py
from django.db import models
from datetime import datetime
from models import networkequipment
from django.core.validators import MaxValueValidator, MinValueValidator
from models import person
from models import client

class OtherNetworkEquipment(networkequipment.NetworkEquipment):
    equipmenttype = models.CharField('Equipment Type', max_length=50, null=False)
    manufacturer = models.CharField('Manufacturer', max_length=40, null=True, default='', blank=True)
    model = models.CharField('Model', max_length=40, null=True, default='', blank=True)
    serialnumber = models.CharField('Serial number', max_length=50, null=True, default='', blank=True)
    
    def __str__(self):
        return self.equipmenttype

models/othernetequipform.py
from django import forms
from models import othernetequip
from models import client
from clientmanagement import views as main_views
from django.urls import reverse
from django.shortcuts import render, render_to_response, redirect
from datetime import datetime

class OtherNetworkEquipmentForm(forms.ModelForm):

    class Meta:
        model = othernetequip.OtherNetworkEquipment
        fields = ('equipmenttype', 'manufacturer', 'model', 'serialnumber', 'connection_type', 'ip_type', 'ip_address', 'mac_address', 'company', 'description')

class OtherNetworkEquipmentFullForm(forms.ModelForm):

    class Meta:
        model = othernetequip.OtherNetworkEquipment
        fields = ('equipmenttype', 'manufacturer', 'model', 'serialnumber', 'connection_type', 'ip_type', 'ip_address', 'mac_address', 'company', 'description')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # if 'instance' in kwargs:
        #     self.fields['user'].queryset = kwargs['instance'].company.employees.all().order_by('firstname', 'lastname')


def otherNetEquipFormParse(request, clientid):    
    valid, response = main_views.initRequest(request)
    if not valid:
        return response
    data={}
    data['PAGE_TITLE'] = 'Change Network Equipment: CMS infotek'
    try:
        b=client.Client.objects.get(id=clientid)
    except Exception as exc:
        return redirect(reverse('allclients'))
    if (request.method == 'POST') and ('action' in request.POST):
        if (request.POST['action']=='add'):
            form = OtherNetworkEquipmentForm(request.POST)
            if form.is_valid():
                model = form.save(commit=False)
                model.save()
                return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
            else:
                data['action']='add'
                data['PAGE_TITLE'] = 'New Network Equipment: CMS infotek'
                data['minititle'] = 'Add Network Equipment'
                data['submbutton'] = 'Add network equipment'
        elif (request.POST['action']=='change'):
            if('targetid' in request.POST):
                try:
                    curequip=othernetequip.OtherNetworkEquipment.objects.get(id=request.POST['targetid'])
                except Exception:
                    return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
                form = OtherNetworkEquipmentFullForm(instance=curequip)
                data['action'] = 'changed'
                data['targetid'] = request.POST['targetid']
                data['minititle'] = 'Change Network Equipment "'+curequip.equipmenttype+'"'
                data['submbutton'] = 'Change network equipment'
                data['deletebutton'] = 'Delete ' + curequip.equipmenttype
            else:
                return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
        elif (request.POST['action']=='changed'):
            if('targetid' in request.POST):
                try:
                    curequip=othernetequip.OtherNetworkEquipment.objects.get(id=request.POST['targetid'])
                except Exception:
                    return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
                form = OtherNetworkEquipmentFullForm(instance=curequip)
                if form.is_valid():
                    model = form.save(commit=False)
                    model.save()
                    return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
                form = OtherNetworkEquipmentFullForm(instance=curequip)
                data['action'] = 'changed'
                data['targetid'] = request.POST['targetid']
                data['minititle'] = 'Change Network Equipment "'+curequip.equipmenttype+'"'
                data['submbutton'] = 'Change network equipment'
                data['deletebutton'] = 'Delete ' + curequip.equipmenttype
            else:
                return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
        elif (request.POST['action']=='delete'):
            if('targetid' in request.POST):
                try:
                    curequip=othernetequip.OtherNetworkEquipment.objects.get(id=request.POST['targetid'])
                except Exception:
                    return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
                curequip.delete()
                return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
            else:
                return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
        else:
            return redirect(reverse('oneclient', kwargs={'clientid': clientid}))
    else:
        form = OtherNetworkEquipmentForm(initial={'company': b})
        data['action']='add'
        data['PAGE_TITLE'] = 'New Network Equipment: CMS infotek'
        data['minititle'] = 'Add Network Equipment'
        data['submbutton'] = 'Add network equipment'
    data['form'] = form
    data['built'] = datetime.now().strftime("%H:%M:%S") 
    data['backurl'] = reverse('oneclient', kwargs={'clientid': clientid})
    return render(request, 'forms/unimodelform.html', data, content_type='text/html')

models/printer.py
from django.db import models
from datetime import datetime
from models import networkequipment
from django.core.validators import MaxValueValidator, MinValueValidator
from models import person
from models import client

class Printer(networkequipment.NetworkEquipment):
    PRINTER_TYPE = (
        ('BL', 'Black and white, Laser'),
        ('CL', 'Color, Laser'),
        ('BI', 'Black and white, Ink'),
        ('CI', 'Color, Ink'),
        ('L', 'Label'),
        ('O', 'Other'),
    )
    MANUFACTURER = (
        ('H', 'HP'),
        ('S', 'Samsung'),
        ('B', 'Brothers'),
        ('C', 'Canon'),
        ('X', 'Xerox'),
        ('D', 'Dymo'),
        ('O', 'Other')
    )
    printername = models.CharField('Printer Name', max_length=50, null=False)
    manufacturer = models.CharField(max_length=1, null=False, default='H', blank=False, choices=MANUFACTURER)
    printertype = models.CharField(max_length=2, null=False, default='BL', blank=False, choices=PRINTER_TYPE)
    model = models.CharField(max_length=50, null=True, default='', blank=True)
    prmonth = models.IntegerField("Recieved Month (enter a number)", blank=True, null=True, default=datetime.today().month, validators=[MaxValueValidator(12), MinValueValidator(1)])
    pryear = models.IntegerField("Recieved Year (enter a number)", blank=True, null=True, default=datetime.today().year, validators=[MaxValueValidator(2030), MinValueValidator(2000)])
    serialnumber = models.CharField(max_length=40, null=True, default='', blank=True)
    
    def __str__(self):
        return self.printername

clientmanagement/testmodule/views.py
"""
Django views for testmodule as an example of Django project structure
"""

from datetime import datetime
from django.shortcuts import render_to_response
from django.utils.cache import patch_response_headers
from clientmanagement.views import initRequest

def testmodule(request):
    valid, response = initRequest(request)
    if not valid: return response

    data = {
            'request': request,
            'built': datetime.now().strftime("%H:%M:%S"),
            }

    response = render_to_response('testModule.html', data, content_type='text/html')
    patch_response_headers(response, cache_timeout=request.session['max_age_minutes'] * 60)
    return response

clientmanagement/templates/views/modals/computermodal.html
<div class="reveal" id="{{ modalpre }}{{ computer.id }}" data-reveal>
    <h3>{{ computer.computername }}</h3>
    <p><b>Operating System:</b> {{ computer.get_operatingsystem_display }}</p>
    {% if computer.compyear %}
    <p><b>Computer recieved:</b> {% if computer.compmonth %}{{ computer.compmonth }}/{% endif %}{{ computer.compyear }}</p>
    {% endif %}
    <p><b>Manufacturer:</b> {{ computer.get_manufacturer_display }}</p>
    {% if computer.model %}
    <p><b>Model:</b> {{ computer.model }}</p>
    {% endif %} {% if computer.serialnumber %}
    <p><b>Serial number:</b> {% if computer.manufacturer == 'D' %}
        <a href="https://www.dell.com/support/home/us/en/19/product-support/servicetag/{{ computer.serialnumber }}/diagnose" target="_blank">{{ computer.serialnumber }}</a> {% else %} {{ computer.serialnumber }} {% endif %}</p>
    {% endif %}
    {% include "views/components/networkeqinfo.html" with equipment=computer %}
    {% if clid %}<form 
        action="{% url 'clientcomputer' clientid=clid %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="change">
        <input type="hidden" name="targetid" value="{{ computer.id }}">
        <a id="comb{{ modalpre }}{{computer.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Change computer info</a>
    </form>
    {% else %}
    {% endif %}
    <a class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </a>
</div>

clientmanagement/templates/views/modals/othernetequip.html
<div class="reveal" id="{{ modalpre }}{{ equipment.id }}" data-reveal>
    <h3>{{ equipment.equipmenttype }}</h3>
    {% if equipment.manufacturer %}
    <p><b>Manufacturer:</b> {{ equipment.manufacturer }}</p>
    {% endif %}
    {% if equipment.model %}
    <p><b>Model:</b> {{ equipment.model }}</p>
    {% endif %} 
    {% if equipment.serialnumber %}
    <p><b>Serial number:</b>{{ equipment.serialnumber }}</p>
    {% endif %} 
    {% include "views/components/networkeqinfo.html" with equipment=equipment %}
    <form action="{% url 'clientothernetequip' clientid=clid %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="change">
        <input type="hidden" name="targetid" value="{{ equipment.id }}">
        <a id="nwqpm{{ modalpre }}{{equipment.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Change equipment info</a>
    </form>
    <a class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </a>
</div>

clientmanagement/templates/views/modals/personmodal.html
<div class="reveal" id="{{ modalpre }}{{ person.id }}" data-reveal>
    <h3>{{ person.name }}</h3>
    <p><b>First name:</b> {{ person.firstname }}</p>
    <p><b>Last name:</b> {{ person.lastname }}</p>
    {% if person.email %}
    <p><b>Email:</b> <a href="mailto:{{ person.email }}">{{ person.email }}</a></p>
    {% endif %} {% if person.phone %}
    <p><b>Phone:</b> {% include "views/components/phonenumber.html" with phone=person.phone %}</p>
    {% endif %}
    <p><b>Annoyance level:</b> <span {% comment %} {% if person.annoyance> 5 %}class="alert"{% endif %} {% endcomment %}> {{ person.annoyance }}</span></p>
    {% if fullinfo %}
    <p><b>Company name:</b> {{ person.employedby.name }}</p>
    {% endif %}
    {% if person.description %}
    <p><b>Description:</b> {{ person.description }}</p>
    {% endif %}
    {% if not fullinfo %}
    <form action="{% url 'clientperson' clientid=clid %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="change">
        <input type="hidden" name="targetid" value="{{ person.id }}">
        <a id="perb{{ modalpre }}{{person.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Change person info</a>
    </form>
    {% endif %}
    <a class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </a>
</div>

clientmanagement/templates/views/modals/printermodal.html
<div class="reveal" id="{{ modalpre }}{{ printer.id }}" data-reveal>
    <h3>{{ printer.printername }}</h3>
    {% if printer.pryear %}
    <p><b>Printer recieved:</b> {% if printer.prmonth %}{{ printer.prmonth }}/{% endif %}{{ printer.pryear }}</p>
    {% endif %} {% if printer.printertype %}
    <p><b>Type:</b> {{ printer.get_printertype_display }}</p>
    {% endif %}
    <p><b>Manufacturer:</b> {{ printer.get_manufacturer_display }}</p>
    {% if printer.model %}
    <p><b>Model:</b> {{ printer.model }}</p>
    {% endif %} {% if printer.serialnumber %}
    <p><b>Serial number:</b>{{ printer.serialnumber }}</p>
    {% endif %} 
    {% include "views/components/networkeqinfo.html" with equipment=printer %}
    <form action="{% url 'clientprinter' clientid=clid %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="change">
        <input type="hidden" name="targetid" value="{{ printer.id }}">
        <a id="printerb{{ modalpre }}{{printer.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Change printer info</a>
    </form>
    <a class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </a>
</div>

clientmanagement/templates/views/modals/ticketmodal.html
<div class="reveal" id="{{ modalpre }}{{ ticket.id }}" data-reveal>
    <h3>{{ ticket.title }}</h3>
    <p><b>Opened on:</b> {{ ticket.createtime|date:"Y-m-d h:i a" }}</p>
    {% if ticket.resolved %}
    <p><b>Closed on:</b> {{ ticket.closetime|date:"Y-m-d h:i a"}}</p>
    <p><b>Closed by:</b> {{ ticket.resolvedby }}</p>
    {% endif %}
    {% if ticket.assignedto %}
    <p><b>Assigned to:</b> {{ ticket.assignedto.get_full_name }}</p>
    {% endif %}
    {% if ticket.companyname %}
    <p><b>Company name:</b> {{ ticket.companyname }}</p>
    {% endif %}
    {% if ticket.contactname %}
    <p><b>Contact:</b> {{ ticket.contactname }}</p>
    {% endif %}
    {% if ticket.contactemail %}
    <p><b>Contact email:</b> <a href="{{ ticket.get_email_link }}">{{ ticket.contactemail }}</a></p>
    {% endif %}
    {% if ticket.contactphone %}
    <p><b>Phone number:</b> {% include "views/components/phonenumber.html" with phone=ticket.contactphone %}</p>
    {% endif %}
    {% if ticket.description %}
    <p><b>Description:</b></p>
    {% include "forms/widget/maybequill.html" with obj=ticket %}<br>
    {% endif %}
    {% if ticket.resolved %}
    <form action="{% url 'ticket_change' ticketid=ticket.id %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="open">
        <a id="open-button-{{ modalpre }}{{ticket.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Reopen ticket</a>
    </form>
    {% else %}
    <form action="{% url 'ticket_change' ticketid=ticket.id %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="close">
        <a id="close-button-{{ modalpre }}{{ticket.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Close ticket</a>
    </form>
    {% endif %}
    <form action="{% url 'ticket_change' ticketid=ticket.id %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="action" value="change">
        <a id="change-button-{{ modalpre }}{{ticket.id}}" class="button round inlineblock" onclick="this.parentElement.submit();">Change ticket</a>
    </form>
    <a class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </a>
</div>